#define BallStartPlayer 0
#define BallStartBot 1
#define BallMovePlayer 2
#define BallMoveBot 3
#define UpRight 0
#define DownRight 1
#define UpLeft 2
#define DownLeft 3
#define FromPlayer 1
#define FromBot 2
#define None 3
#define Up 0
#define Down 1
#define SpeedY 4
#define SpeedX 3
#define PadSpeed 6
